services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: perspective-microservice
    ports:
      - "3001:3000"
    restart: unless-stopped
    container_name: perspective-microservice
