name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "API_KEY_PERSPECTIVE=${{ secrets.API_KEY_PERSPECTIVE }}" >> .env
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env

      - name: check env file and variables
        run: |
          cat .env
          ls

      - name: Build project
        run: pnpm run build
      - name: Copy Docker files
        run: |
          cp docker-compose.yml dist/
          cp Dockerfile dist/

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist/*"
          target: ${{ secrets.TARGETPATH }}

      - name: Run Docker Compose on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.TARGETPATHDOCKER }}
            docker compose up -d
